name: Trigger Fork Repo Action

on:
  push:
    branches:
      - main

jobs:
  trigger-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository_dispatch
        if: github.organization == 'gugumo-service'
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.PAT }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          "https://api.github.com/repos/Banal972/gugumo_frontend_new/dispatches" \
          -d '{"event_type": "main_updated"}'
